### ISSUE TITLE
import error from csvreader.py

### ISSUE THREAD

**Issue by philbarker** [tombaker/csv2shex#6]
Context: I'm using csv2shex as a git submodule, it's in a subdirectory of my project.

I get the error
```
    from csv2shex.exceptions import CsvError
ModuleNotFoundError: No module named 'csv2shex'
```
which I can fix by chaging 
`from csv2shex.exceptions import CsvError`
to
`from .exceptions import CsvError`

Is this because csv2shex isn't at the top level of the project, or are you relying on python path for this import to work?

**Comment by tombaker** [comment]
@philbarker I'm not sure why this is. Generally, I have used the `.exceptions` pattern for importing between modules within the package, and the `csv2shex.exceptions` pattern for the tests. But at some point I found that I needed to add the `csv2shex.` part to make something work. Quite possibly this was when I was doing edit-debug in IPython (not Jupyter Notebook) and importing the modules separately.

At any rate, none of the tests break if I remove `csv2shex`, so I have done this. AFAIK csv2shex is at the "top level" of the project, though I'm not sure I understand exactly what that means. And I never use python path.

Please let me know if this solves your problem.

**Comment by philbarker** [comment]
problem has gone now that I am using `pip install` from the repo as a dependency rather than having a git subrepository. I chalk it up to being one of those issues that I found a way to avoid rather than understand.
